import { Globe, Bot, BarChart2, FileText, Zap, TrendingUp, Sparkles, BookOpen } from "lucide-react";

export const BLOG_POSTS = [
  {
    slug: "ai-chatbot-african-businesses-2025",
    title: "Why Every African Business Needs an AI Agent in 2025",
    excerpt: "Customer expectations are shifting fast across Rwanda, Kenya, and Nigeria. Businesses that respond instantly win. Here's how AI agents are changing the game.",
    category: "Industry",
    categoryColor: "#38AECC",
    readTime: "5 min read",
    date: "Jan 15, 2025",
    featured: true,
    icon: Globe,
    tags: ["AI", "Africa", "Customer Service"],
    gradient: "linear-gradient(135deg, #060E18 0%, #0D2235 100%)",
    accentColor: "#38AECC",
  },
  {
    slug: "how-to-train-your-ai-agent-velamini",
    title: "How to Train Your Velamini Agent to Sound Like Your Brand",
    excerpt: "A step-by-step guide to writing the perfect system prompt, setting welcome messages, and building a Q&A library that makes your agent feel human.",
    category: "Tutorial",
    categoryColor: "#34D399",
    readTime: "8 min read",
    date: "Jan 10, 2025",
    featured: false,
    icon: Bot,
    tags: ["Tutorial", "Agent Setup", "Prompting"],
    gradient: "linear-gradient(135deg, #060E18 0%, #0A1E14 100%)",
    accentColor: "#34D399",
  },
  {
    slug: "velamini-data-insights-pos-restaurants",
    title: "From POS Export to Business Intelligence in 60 Seconds",
    excerpt: "Upload your sales CSV, and Velamini's AI instantly surfaces your top sellers, peak hours, slow movers, and reorder alerts — no spreadsheet skills needed.",
    category: "Product",
    categoryColor: "#818CF8",
    readTime: "6 min read",
    date: "Jan 5, 2025",
    featured: false,
    icon: BarChart2,
    tags: ["Data Insights", "Analytics", "POS"],
    gradient: "linear-gradient(135deg, #060E18 0%, #0D0E28 100%)",
    accentColor: "#818CF8",
  },
  {
    slug: "ai-resume-builder-job-seekers-rwanda",
    title: "Get Hired Faster: Using Velamini to Build a Standout CV",
    excerpt: "Your personal Velamini agent can write, review, and tailor your resume for any job. Here's how thousands of job seekers in Rwanda are using it.",
    category: "Personal",
    categoryColor: "#F59E0B",
    readTime: "4 min read",
    date: "Dec 28, 2024",
    featured: false,
    icon: FileText,
    tags: ["Resume", "Career", "Personal AI"],
    gradient: "linear-gradient(135deg, #060E18 0%, #1A1200 100%)",
    accentColor: "#F59E0B",
  },
  {
    slug: "embed-ai-agent-website-5-minutes",
    title: "Add an AI Agent to Any Website in Under 5 Minutes",
    excerpt: "One script tag. That's all it takes to embed Velamini on your website. No backend, no framework required. A complete walkthrough with real examples.",
    category: "Tutorial",
    categoryColor: "#34D399",
    readTime: "5 min read",
    date: "Dec 20, 2024",
    featured: false,
    icon: Zap,
    tags: ["Tutorial", "Embed", "No-Code"],
    gradient: "linear-gradient(135deg, #060E18 0%, #0A1E14 100%)",
    accentColor: "#34D399",
  },
  {
    slug: "velamini-vs-tidio-vs-intercom-africa",
    title: "Velamini vs Tidio vs Intercom: Which AI Chat Tool Works Best in Africa?",
    excerpt: "We compared pricing, payment methods, latency, language support, and local integrations. The results might surprise you.",
    category: "Comparison",
    categoryColor: "#EC4899",
    readTime: "10 min read",
    date: "Dec 15, 2024",
    featured: false,
    icon: TrendingUp,
    tags: ["Comparison", "Tools", "Africa"],
    gradient: "linear-gradient(135deg, #060E18 0%, #1A0818 100%)",
    accentColor: "#EC4899",
  },
  {
    slug: "message-quota-optimization-tips",
    title: "10 Ways to Get More Value from Your Monthly Message Quota",
    excerpt: "Smarter caching, fallback responses, quick-reply chips, and other techniques that cut unnecessary AI calls while improving your customer experience.",
    category: "Tips",
    categoryColor: "#38AECC",
    readTime: "7 min read",
    date: "Dec 8, 2024",
    featured: false,
    icon: Sparkles,
    tags: ["Optimization", "Tips", "Quota"],
    gradient: "linear-gradient(135deg, #060E18 0%, #0D2235 100%)",
    accentColor: "#38AECC",
  },
  {
    slug: "velamini-api-rest-integration-guide",
    title: "The Complete Velamini REST API Guide for Developers",
    excerpt: "Authentication, rate limits, streaming responses, webhook events, and error handling — everything you need to integrate Velamini into your own product.",
    category: "Developers",
    categoryColor: "#818CF8",
    readTime: "12 min read",
    date: "Dec 1, 2024",
    featured: false,
    icon: BookOpen,
    tags: ["API", "Developers", "Integration"],
    gradient: "linear-gradient(135deg, #060E18 0%, #0D0E28 100%)",
    accentColor: "#818CF8",
  },
];

export const CATEGORIES = ["All", "Industry", "Tutorial", "Product", "Personal", "Comparison", "Tips", "Developers"] as const;
